# Generated by Django 4.1 on 2022-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='listingprice',
            field=models.CharField(max_length=50),
        ),
    ]
