# Generated by Django 4.1 on 2022-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_adminuser_terms_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, upload_to='blog_images')),
            ],
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='terms_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
