# Generated by Django 4.1 on 2022-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='img',
            field=models.FileField(blank=True, upload_to='blog_images'),
        ),
    ]
