# Generated by Django 4.1 on 2022-08-31 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_addproperty_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='adminuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.adminuser'),
        ),
    ]
